version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tu_contraseña_segura
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
volumes:
  mysql_data:
